// Hash-keyed cache of AI enhancements. Re-opening the same session (same
// content hash) and repo reuses the cached result, so re-exports are
// byte-identical instead of regenerated by the model — same guarantee the
// share cache gives share links, and same eviction shape (capped, oldest
// first, tiny entries only).

import { AI_CACHE_KEY } from './constants.ts';
import { sanitizeAIResult, type AIResult } from './ai-merge.ts';
import { getStorageArea } from './storage.ts';

interface CachedAIResult {
  result: AIResult;
  createdAt: number;
}

const MAX_CACHED = 100;

// The pass that produced the cached result. Distinct passes must never
// collide on the same session: the title pass fires at review load (repo-blind),
// while the enhance pass fires in the issue dialog. A cached title-only entry
// would otherwise be misread as a full enhancement.
export type AICacheKind = 'title' | 'enhance';

// Cache key: namespaced by pass kind, keyed on the session's content hash
// (title excluded, matching the share hash). The enhance pass appends the
// repo so a repo change re-enhances; the repo-blind passes never carry one.
export function aiCacheKey(kind: AICacheKind, sessionHash: string, repo = ''): string {
  return `${kind}:${sessionHash}${repo ? `:${repo}` : ''}`;
}

export async function getCachedAIResult(key: string): Promise<AIResult | null> {
  const storage = getStorageArea();
  const { [AI_CACHE_KEY]: cache } = await storage.get(AI_CACHE_KEY);
  const entry = (cache as Record<string, CachedAIResult> | undefined)?.[key];
  if (!entry) return null;
  // Re-validate on read: a corrupted entry degrades to a fresh generation.
  return sanitizeAIResult(JSON.stringify(entry.result));
}

export async function rememberAIResult(key: string, result: AIResult): Promise<void> {
  const storage = getStorageArea();
  const { [AI_CACHE_KEY]: cache } = await storage.get(AI_CACHE_KEY);
  const next: Record<string, CachedAIResult> = {
    ...(cache as Record<string, CachedAIResult> | undefined),
    [key]: { result, createdAt: Date.now() },
  };
  const entries = Object.entries(next).sort((a, b) => a[1].createdAt - b[1].createdAt);
  while (entries.length > MAX_CACHED) delete next[entries.shift()![0]];
  await storage.set({ [AI_CACHE_KEY]: next });
}
