export const POST_MESSAGE_KEY = '__trail__';
export const RECORDER_ID = 'trail-recorder';

// The command the overlay posts to the MAIN-world recorder to emit a flag
// event (payload `d: { expected?, actual? }`). Uses the same postMessage
// channel as the relay's start/stop commands.
export const FLAG_KEY = 'flag';

export const DB_NAME = 'trail';
export const EVENTS_STORE = 'events';
export const REPORTS_STORE = 'reports';
export const SESSIONS_STORE = 'sessions';

export const MSG_BATCH = 'trail:batch';
export const MSG_START = 'trail:start';
export const MSG_STOP = 'trail:stop';
export const MSG_STATUS = 'trail:status';
export const MSG_OVERLAY_STATUS = 'trail:overlay-status';
export const MSG_OVERLAY_UPDATE = 'trail:overlay-update';
export const MSG_REDACT = 'trail:redact';
export const MSG_STOP_RECORDER = 'trail:stop-recorder';
export const MSG_START_RECORDER = 'trail:start-recorder';
// Web page → relay → background: a page on WEB_ORIGIN asks the extension to
// open a shared session (the handoff button in the web app's /r/<id> page).
export const MSG_OPEN_SHARE = 'trail:open-share';

// chrome.storage.local keys for persisted preferences
export const REDACT_KEY = 'trail:autoRedact';
// Previously-used repos, most recent first — offered as suggestions while the
// user types in the repository field (never autofilled).
export const REPO_HISTORY_KEY = 'trail:repoHistory';
// AI report enhancements: opt-out toggle (default on). The API keys
// (OpenRouter for the report pass, Groq for the title pass) live on the
// replay server — the extension never sees or stores them.
export const AI_ENABLED_KEY = 'trail:aiEnabled';
// chrome.storage.local key for the AI-result cache (session hash + repo →
// AI result). Re-opening the same session reuses the cached enhancement so a
// re-export is byte-identical instead of regenerated by the model.
export const AI_CACHE_KEY = 'trail:aiCache';

// chrome.storage.local key for the share-link cache (hash -> share link).
// Re-sharing an already-shared session reuses its link instead of uploading
// the payload to blob storage a second time.
export const SHARE_CACHE_KEY = 'trail:shareCache';

// Shared-package env reads. The extension inlines WXT_PUBLIC_* at build time,
// the web app inlines NEXT_PUBLIC_* by statically replacing
// `process.env.NEXT_PUBLIC_*` member accesses — a replacement that only works
// for literal accesses (`process.env[key]` lookups survive untouched and then
// throw in the browser, where no `process` exists). Each variable therefore
// gets a dedicated static access below, guarded so bundlers that define no
// `process` (the extension's browser build) short-circuit instead of
// evaluating it. `?? {}` covers runtimes where import.meta.env itself is
// undefined (Next SSR).
const env = (import.meta.env ?? {}) as Record<string, string | undefined>;

const nextPublicEnv = (key: string): string | undefined => {
  if (typeof process === "undefined") return undefined;
  switch (key) {
    case "NEXT_PUBLIC_REPLAY_SERVER_URL":
      return process.env.NEXT_PUBLIC_REPLAY_SERVER_URL;
    case "NEXT_PUBLIC_WEB_URL":
      return process.env.NEXT_PUBLIC_WEB_URL;
    default:
      return undefined;
  }
};

// Base URL of the replay share server (see replay-server/). Points at the local
// twin by default; production builds override via WXT_PUBLIC_REPLAY_SERVER_URL
// (a WXT_PUBLIC_ var, inlined at build time — see the WXT env docs) or the web
// app's NEXT_PUBLIC_REPLAY_SERVER_URL.
export const REPLAY_SERVER_URL =
  env.WXT_PUBLIC_REPLAY_SERVER_URL ??
  env.NEXT_PUBLIC_REPLAY_SERVER_URL ??
  nextPublicEnv("NEXT_PUBLIC_REPLAY_SERVER_URL") ??
  "http://localhost:8898";

// Base URL of the web app (see apps/web). Share links point here — opening
// one works with or without the extension installed (the web page renders the
// review UI and hands off to the extension when it's present). The extension
// builds override the localhost default via WXT_PUBLIC_WEB_URL.
export const WEB_URL =
  env.WXT_PUBLIC_WEB_URL ??
  env.NEXT_PUBLIC_WEB_URL ??
  nextPublicEnv("NEXT_PUBLIC_WEB_URL") ??
  "http://localhost:3000";

// Origin and hostname of the web app — the relay origin-gates the handoff
// bridge on WEB_ORIGIN, and the background validates share links against
// WEB_HOST before opening them.
export const WEB_ORIGIN = new URL(WEB_URL).origin;
export const WEB_HOST = new URL(WEB_URL).hostname;
